/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WS3DApp;

import java.util.Random;
import ws3dproxy.WS3DProxy;
import ws3dproxy.model.Creature;
import ws3dproxy.model.Thing;
import ws3dproxy.model.World;
import ws3dproxy.model.WorldPoint;

public class App {
    
    public WS3DProxy proxy;
    public ControlFrame cf;

    public String getGreeting() {
        return("Greetings...");
    }
    
    public App() {
        proxy = new WS3DProxy();
        cf = new ControlFrame(proxy);
        cf.setVisible(true);
    }
            

    public static void main(String[] args) {
        Random r = new Random();
        App app = new App();
        
        // try {
        //     while(true) {
        //         app.c.moveto(4, r.nextInt(app.width),r.nextInt(app.height));
        //         Thread.sleep(5000);
        //         WorldPoint position = app.c.getPosition();
        //         double pitch = app.c.getPitch();
        //         double fuel = app.c.getFuel();
        //         System.out.println("Creature is at "+position+" with pitch "+pitch+" and fuel "+fuel);
        //         app.c.updateState();
        //         System.out.print("It can see the following from here: ");
        //         for (Thing t : app.c.getThingsInVision()) {
        //             System.out.print(" "+t.getName());
        //         }
        //         System.out.println("");
        //     }
        // } catch (Exception e) {
        //     System.out.println("Erro capturado"); 
        // }
    }
}
