/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WS3DApp;

import ws3dproxy.WS3DProxy;
import ws3dproxy.model.Creature;
import ws3dproxy.model.World;

/**
 *
 * @author ia941
 */
public class ControlFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ControlFrame.class.getName());

    private WS3DProxy proxy;
    private World world;
    private Creature creature;

    /**
     * Creates new form ControlFrame
     */
    public ControlFrame(WS3DProxy proxy) {
        this.proxy = proxy;
        initComponents();
        setupKeyBindings();
        setupTooltips();
        initWorld();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonUp = new javax.swing.JButton();
        jButtonRight = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jButtonLeft = new javax.swing.JButton();
        jButtonDown = new javax.swing.JButton();
        jButtonUp.setFocusable(false);
        jButtonDown.setFocusable(false);
        jButtonLeft.setFocusable(false);
        jButtonRight.setFocusable(false);
        jButtonStop.setFocusable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonUp.setText("↑");
        jButtonUp.addActionListener(this::jButtonUpActionPerformed);

        jButtonRight.setText("→");
        jButtonRight.addActionListener(this::jButtonRightActionPerformed);

        jButtonStop.setText("Stop");
        jButtonStop.addActionListener(this::jButtonStopActionPerformed);

        jButtonLeft.setText("←");
        jButtonLeft.addActionListener(this::jButtonLeftActionPerformed);

        jButtonDown.setText("↓");
        jButtonDown.addActionListener(this::jButtonDownActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setVerticalGroup(
            layout.createSequentialGroup()
                .addGap(40)
                .addComponent(jButtonUp)
                .addGap(20)
                .addGroup(
                    layout.createParallelGroup()
                        .addComponent(jButtonLeft)
                        .addComponent(jButtonStop)
                        .addComponent(jButtonRight)
                )
                .addGap(20)
                .addComponent(jButtonDown)
                .addGap(40)
        );
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jButtonUp)
                .addGroup(
                    layout.createSequentialGroup()
                        .addComponent(jButtonLeft)
                        .addGap(20)
                        .addComponent(jButtonStop)
                        .addGap(20)
                        .addComponent(jButtonRight)
                )
                .addComponent(jButtonDown)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initWorld() {
        try {
            world = World.getInstance();
            world.reset();

            World.createFood(0, 350, 75);
            World.createFood(0, 100, 220);
            World.createJewel(0, 10, 50);
            World.createBrick(3, 500, 200, 505, 300);

            creature = proxy.createCreature(100, 450, 0);
            creature.start();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void jButtonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpActionPerformed
        try {
            creature.move(1, 1, creature.getPitch());
            creature.updateState();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonUpActionPerformed

    private void jButtonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownActionPerformed
        try {
            creature.move(-1, -1, creature.getPitch());
            creature.updateState();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonDownActionPerformed

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownActionPerformed
        try {
            creature.move(0, 0, creature.getPitch());
            creature.updateState();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRightActionPerformed
        try {
            creature.move(-1, 1, creature.getPitch());
            creature.updateState();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonRightActionPerformed

    private void jButtonLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeftActionPerformed
        try {
            creature.move(1, -1, creature.getPitch());
            creature.updateState();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonLeftActionPerformed

    private void setupKeyBindings() {

        var inputMap = getRootPane().getInputMap(
            javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
        );
        var actionMap = getRootPane().getActionMap();

        // UP
        inputMap.put(
            javax.swing.KeyStroke.getKeyStroke("UP"),
            "moveUp"
        );
        actionMap.put("moveUp", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                jButtonUpActionPerformed(null);
            }
        });

        // DOWN
        inputMap.put(
            javax.swing.KeyStroke.getKeyStroke("DOWN"),
            "moveDown"
        );
        actionMap.put("moveDown", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                jButtonDownActionPerformed(null);
            }
        });

        // LEFT
        inputMap.put(
            javax.swing.KeyStroke.getKeyStroke("LEFT"),
            "moveLeft"
        );
        actionMap.put("moveLeft", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                jButtonLeftActionPerformed(null);
            }
        });

        // RIGHT
        inputMap.put(
            javax.swing.KeyStroke.getKeyStroke("RIGHT"),
            "moveRight"
        );
        actionMap.put("moveRight", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                jButtonRightActionPerformed(null);
            }
        });

        // SPACE = STOP
        inputMap.put(
            javax.swing.KeyStroke.getKeyStroke("SPACE"),
            "stop"
        );
        actionMap.put("stop", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                jButtonStopActionPerformed(null);
            }
        });
    }

    private void setupTooltips() {
        javax.swing.ToolTipManager.sharedInstance().setInitialDelay(100);
        javax.swing.ToolTipManager.sharedInstance().setReshowDelay(50);
        javax.swing.ToolTipManager.sharedInstance().setDismissDelay(4000);
        jButtonUp.setToolTipText("Move forward (↑)");
        jButtonDown.setToolTipText("Move backward (↓)");
        jButtonLeft.setToolTipText("Rotate left (←)");
        jButtonRight.setToolTipText("Rotate right (→)");
        jButtonStop.setToolTipText("Stop movement (SPACE)");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUp;
    private javax.swing.JButton jButtonRight;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JButton jButtonLeft;
    private javax.swing.JButton jButtonDown;
    // End of variables declaration//GEN-END:variables
}
